### ISSUE TITLE
BRBseqTools.jar 1.6 Final step of DGEMatrix generation issue

### ISSUE THREAD

**Issue by MathewBerg9** [DeplanckeLab/BRB-seqTools#8]
Hi, I've been trying to use the BRBseqTools, for my BRBseq data with 48 samples. All the steps have until the generation of the BAM file have worked, but when I get to the last step: 
java -jar BRBseqTools.jar CreateDGEMatrix -f lib_example_R1.fastq.gz -b BAM/lib_example_R2.bam -c lib_example_barcodes.txt -gtf Homo_sapiens.GRCh38.90.gtf -p BU -UMI 14 

I get the following error, which I have been unable to fix, my Barcode is 14BP long so is the UMI. Could you help me out?

Exception in thread "main" htsjdk.samtools.FileTruncatedException: Premature end of file: /bharadv/BRBseq/BAM/library_R2.bam
        at htsjdk.samtools.util.BlockCompressedInputStream.processNextBlock(BlockCompressedInputStream.java:513)
        at htsjdk.samtools.util.BlockCompressedInputStream.nextBlock(BlockCompressedInputStream.java:451)
        at htsjdk.samtools.util.BlockCompressedInputStream.readBlock(BlockCompressedInputStream.java:441)
        at htsjdk.samtools.util.BlockCompressedInputStream.available(BlockCompressedInputStream.java:194)
        at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:322)
        at java.io.DataInputStream.read(DataInputStream.java:149)
        at htsjdk.samtools.util.BinaryCodec.readBytesOrFewer(BinaryCodec.java:404)
        at htsjdk.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:380)
        at htsjdk.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:366)
        at htsjdk.samtools.BAMRecordCodec.decode(BAMRecordCodec.java:199)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.getNextRecord(BAMFileReader.java:813)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:787)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:781)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:751)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:569)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:543)
        at DGEMatrixManager.readR2BAM(DGEMatrixManager.java:43)
        at BRBseqTools.main(BRBseqTools.java:43)

**Comment by VincentGardeux** [comment]
It seems that the R2 bam file is truncated. Did you trim it?
If yes, maybe the trimming step failed. Do you have the output of the trimming step?
